### PR TITLE
Fix zh font size

### PR DESCRIPTION
**Pull request by hong0311**
- Please use the numberings (i.e. '1.') and with no indent in the md files so it will correctly translated to numbered lists in HTML

- When a new language is added, please update open-letter-page.js for the numbered lists of the corresponding language

### CODE REVIEW

**Comment by mingchuno** [comment]
@hong0311 can you add those point in README too? I think it is important

**Comment by caseykwok** [comment]
@hong0311 do you think we should add some "indent" to each number point for the Chinese version? There's a "default indent" for English version.

**Comment by caseykwok** [comment]
@hong0311 I understand that we will be changing the Japanese version later but do you need to help them format it first right now so the people can just copy and paste the correct content later?

**Comment by hong0311** [comment]
> @hong0311 do you think we should add some "indent" to each number point for the Chinese version? There's a "default indent" for English version.

The indent is actually inscribed nativevly in the ordered list <ol>. The Chinese Characters takes too much space that it took all 4 half spaces, thus different to the English version. Do you want to manually add an indent though?

**Pull request merged**
