### PR TITLE
jp -> ja typo

### PR DESCRIPTION
**Pull request by hong0311**

### CODE REVIEW

**Comment by mingchuno** [comment]
@hong0311 can you open a new branch for your work push again? too easy to conflict

**Comment by mingchuno** [comment]
I have invited you to the repo, you can open a branch and push in this repo, no need to open in fork (which is painful) @hong0311

**Comment by hong0311** [comment]
> I have invited you to the repo, you can open a branch and push in this repo, no need to open in fork (which is painful) @hong0311

It was indeed painful lol
I couldn't find the invitation so I kinda had to fork it every time I commit something. Thankfully I just found the invitation in my email lol

**Comment by mingchuno** [comment]
fixed

**Pull request closed without merging**
