### PR TITLE
Language menu

### PR DESCRIPTION
**Pull request by demopaxlee**

### CODE REVIEW

**Comment by gaplo917** [comment]
@demopaxlee if you attempt to refactor to ES6 modules, all gatsby pipeline has to be refactor  too. As gatsby won't allow mixed modules.

**Comment by gaplo917** [comment]
which included `gatsby-config` ,`gatsby-node`, `gatsby-ssr`, `gatsby-browser`

**Comment by demopaxlee** [comment]
Oh I see. Will switch back

**Comment by caseykwok** [comment]
Do you think we should apply `text-decoration: none` to the language links?

**Comment by demopaxlee** [comment]
@gaplo917 @mingchuno

**Comment by gaplo917** [comment]
tested `gatsby build && gatsby serve`. it works!

**Comment by gaplo917** [comment]
@demopaxlee as a reminder, I change the fontAwesome icon to material design icon.

**Pull request merged**
