### PR TITLE
Update about-de.md

### PR DESCRIPTION
**Pull request by KayiuCheung**
initiate update on German content based on https://docs.google.com/document/d/18Nz7Rgh57W1qS92X0jI8-w4PMMfw_Pm4hEW62WvjuPo/edit#

### CODE REVIEW

**Comment by mingchuno** [comment]
@KayiuCheung conflict, can you resolve and recommit? or resubmit a new one

**Comment by j5891m** [comment]
Please merge it first. Text needed to be amended and will pull again later today.

**Comment by mingchuno** [comment]
cant merge due to conflict.... @j5891m

**Comment by KayiuCheung** [comment]
@mingchuno is it possible to ignore pick out this PR first? it isn't related ja update

**Comment by caseykwok** [comment]
According to @j5891m, the file for `About Me` section in development right now is already the most updated, so I will close this PR.

cc @KayiuCheung @mingchuno

**Pull request closed without merging**
